# Generated by Django 3.1.4 on 2022-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('hire_date', models.DateField(auto_now=True)),
                ('job_id', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=50)),
                ('comission_pct', models.IntegerField(max_length=100)),
                ('manager_id', models.IntegerField(max_length=50)),
                ('department_id', models.IntegerField(max_length=50)),
            ],
        ),
    ]
