# Generated by Django 3.1.4 on 2022-06-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='comission_pct',
        ),
        migrations.AddField(
            model_name='worker',
            name='commission_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='manager_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('speciality', models.ManyToManyField(to='workers.Paradigm')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='paradigm',
            field=models.ForeignKey(blank=None, default='', on_delete=django.db.models.deletion.CASCADE, to='workers.paradigm'),
            preserve_default=False,
        ),
    ]
