# Generated by Django 3.1.4 on 2022-06-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20220617_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='comission_pct',
            new_name='commission_pct',
        ),
    ]
