# Generated by Django 3.1.4 on 2022-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20220618_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradigm',
            old_name='first_name',
            new_name='speciality',
        ),
    ]
