# Generated by Django 4.0.4 on 2022-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_speciality_rename_email_worker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='commission_pct',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='department_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='job',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='manager_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
