# Generated by Django 3.1.4 on 2022-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20220618_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(to='workers.Worker'),
        ),
    ]
