# Generated by Django 4.0.4 on 2022-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='speciality',
            field=models.ManyToManyField(blank=True, null=True, to='workers.speciality'),
        ),
    ]
