# Generated by Django 3.1.4 on 2022-06-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20220618_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
            preserve_default=False,
        ),
    ]
