# Generated by Django 4.0.4 on 2022-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_worker_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='commission_pct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='manager_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
