# Generated by Django 3.1.4 on 2022-06-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20220618_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradigm',
            old_name='jobs',
            new_name='speciality',
        ),
    ]
