# Generated by Django 3.1.4 on 2022-06-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20220618_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='speciality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workers.paradigm'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='worker',
            name='job_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='job_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
