# Generated by Django 3.1.4 on 2022-06-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20220624_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='paradigm',
            new_name='name',
        ),
    ]
