# Generated by Django 3.1.4 on 2022-06-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_auto_20220624_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='name',
            new_name='paradigm',
        ),
    ]
